import logging

INITIAL_WAIT_TIMEOUT = 15
SCROLL_PAUSE_TIME = 2
LOG_LEVEL = logging.DEBUG

DIRECTORY_DATA = "data"
DIRECTORY_CHARTS = f"{DIRECTORY_DATA}/charts"

OUTPUT_FILENAME = "techinasia_jobs_master.csv"
OUTPUT_FILENAME_SANITISED = "techinasia_jobs_sanitised.csv"
OUTPUT_PATH_REPORT = f"{DIRECTORY_DATA}/quality_report.csv"
OUTPUT_PATH_SANITISED = f"{DIRECTORY_DATA}/{OUTPUT_FILENAME_SANITISED}"

OUTPUT_PATH = f"{DIRECTORY_DATA}/{OUTPUT_FILENAME}"
OUTPUT_PATH_CHART_JOBS_PER_DAY = f"{DIRECTORY_CHARTS}/bar_jobs_per_day.png"
OUTPUT_PATH_CHART_SALARY = f"{DIRECTORY_CHARTS}/histogram_salary.png"
OUTPUT_PATH_CHART_TOP_COMPANIES = f"{DIRECTORY_CHARTS}/bar_top_companies.png"
