name: Every 5 minutes scrape

on:
  schedule:
    - cron:  '*/5 * * * *'        # UTC; same as local schedule  [oai_citation:3‡jasonet.co](https://jasonet.co/posts/scheduled-actions/?utm_source=chatgpt.com)
  workflow_dispatch:            # manual “Run workflow” button in UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          # fetch repo  [oai_citation:4‡github.com](https://github.com/actions/setup-python?utm_source=chatgpt.com)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'           # keep in sync with your venv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full pipeline
        run: python run_pipeline.py

      - name: Upload artefacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-data
          path: |
            data/techinasia_jobs_*.csv
            data/charts/*.png

      # OPTIONAL — commit sanitised CSV back to repo
      - name: Commit & push cleaned data
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name  "gha-bot"
          git config --global user.email "gha@users.noreply.github.com"
          git add data/*.csv
          git commit -m "GH Action: update data (`date -u '+%Y-%m-%d %H:%M'`)" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # auto-scoped token  [oai_citation:5‡docs.github.com](https://docs.github.com/actions/security-guides/automatic-token-authentication?utm_source=chatgpt.com)
